/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/ui/AboutDialog.vue')['default']
    AlterTableDialog: typeof import('./src/components/ui/AlterTableDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ConnectionContextMenu: typeof import('./src/components/sidebar/ConnectionContextMenu.vue')['default']
    ConnectionNode: typeof import('./src/components/sidebar/ConnectionNode.vue')['default']
    ContextMenu: typeof import('./src/components/ui/ContextMenu.vue')['default']
    CreateDatabaseDialog: typeof import('./src/components/ui/CreateDatabaseDialog.vue')['default']
    CreateSchemaDialog: typeof import('./src/components/ui/CreateSchemaDialog.vue')['default']
    CreateTableDialog: typeof import('./src/components/ui/CreateTableDialog.vue')['default']
    DatabaseContextMenu: typeof import('./src/components/sidebar/DatabaseContextMenu.vue')['default']
    DatabaseNode: typeof import('./src/components/sidebar/DatabaseNode.vue')['default']
    DatabaseTree: typeof import('./src/components/sidebar/DatabaseTree.vue')['default']
    DataGrid: typeof import('./src/components/grid/DataGrid.vue')['default']
    DbIcon: typeof import('./src/components/icons/DbIcon.vue')['default']
    Docker: typeof import('./src/components/ui/Docker.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/DropdownMenu.vue')['default']
    ExportConnectionsModal: typeof import('./src/components/modals/ExportConnectionsModal.vue')['default']
    GlobalErrorDialog: typeof import('./src/components/ui/GlobalErrorDialog.vue')['default']
    GridCell: typeof import('./src/components/grid/GridCell.vue')['default']
    GridHeaderCell: typeof import('./src/components/grid/GridHeaderCell.vue')['default']
    GridToolbar: typeof import('./src/components/grid/GridToolbar.vue')['default']
    ImportConnectionsModal: typeof import('./src/components/modals/ImportConnectionsModal.vue')['default']
    IndexDetails: typeof import('./src/components/layout/IndexDetails.vue')['default']
    IndexesPanel: typeof import('./src/components/panels/IndexesPanel.vue')['default']
    InputDialog: typeof import('./src/components/ui/InputDialog.vue')['default']
    MinimizedDock: typeof import('./src/components/layout/MinimizedDock.vue')['default']
    NewConnectionModal: typeof import('./src/components/modals/NewConnectionModal.vue')['default']
    ObjectGroupNode: typeof import('./src/components/sidebar/ObjectGroupNode.vue')['default']
    OutputPanel: typeof import('./src/components/panels/OutputPanel.vue')['default']
    Pagination: typeof import('./src/components/grid/Pagination.vue')['default']
    PanelHeader: typeof import('./src/components/layout/PanelHeader.vue')['default']
    PreferencesModal: typeof import('./src/components/modals/PreferencesModal.vue')['default']
    PropertiesPanel: typeof import('./src/components/panels/PropertiesPanel.vue')['default']
    ResizeHandle: typeof import('./src/components/ui/ResizeHandle.vue')['default']
    ResultsGrid: typeof import('./src/components/sql/ResultsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaContextMenu: typeof import('./src/components/sidebar/SchemaContextMenu.vue')['default']
    SchemaDiagram: typeof import('./src/components/layout/SchemaDiagram.vue')['default']
    SchemaNode: typeof import('./src/components/sidebar/SchemaNode.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SidebarDialogs: typeof import('./src/components/sidebar/SidebarDialogs.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
    SqlEditor: typeof import('./src/components/sql/SqlEditor.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TabContent: typeof import('./src/components/layout/TabContent.vue')['default']
    TableColumnsEditor: typeof import('./src/components/ui/TableColumnsEditor.vue')['default']
    TableConstraintsEditor: typeof import('./src/components/ui/TableConstraintsEditor.vue')['default']
    TableContextMenu: typeof import('./src/components/sidebar/TableContextMenu.vue')['default']
    TableNode: typeof import('./src/components/sidebar/TableNode.vue')['default']
    TabSelectorDialog: typeof import('./src/components/ui/TabSelectorDialog.vue')['default']
    TimelinePanel: typeof import('./src/components/panels/TimelinePanel.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    ToastContainer: typeof import('./src/components/ui/ToastContainer.vue')['default']
    ToastMessage: typeof import('./src/components/ui/ToastMessage.vue')['default']
    ToggleSwitch: typeof import('./src/components/ui/ToggleSwitch.vue')['default']
    UpdaterDialog: typeof import('./src/components/ui/UpdaterDialog.vue')['default']
    ValueViewer: typeof import('./src/components/panels/ValueViewer.vue')['default']
    WorkspaceContainer: typeof import('./src/components/layout/WorkspaceContainer.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
