// src/stores/grid/useNewRow.ts
import { BridgeService } from '@/services/bridge';
import type { GridColumn, GridRow } from '@/types';
import { ref, type Ref } from 'vue';
import { useToastStore } from '../toast';
import { parseGridInputValue } from './valueConversion';

export function useNewRow(
  rows: Ref<GridRow[]>,
  columns: Ref<GridColumn[]>,
  totalRows: Ref<number>,
  activeConnectionId: Ref<string | null>,
  activeTableName: Ref<string>,
  resolveBackendTableName: (name: string) => string
) {
  const toastStore = useToastStore();
  const newRowIdx = ref<number | null>(null);
  const newRowData = ref<Record<string, string>>({});
  const newRowErrors = ref<Record<string, string>>({});

  const createNewRow = () => {
    const placeholder: GridRow = {};
    for (const col of columns.value) {
      placeholder[col.name] = '';
    }
    rows.value = [placeholder, ...rows.value];
    totalRows.value += 1;
    newRowIdx.value = 0;
    const data: Record<string, string> = {};
    for (const col of columns.value) {
      data[col.name] = '';
    }
    newRowData.value = data;
  };

  const cancelNewRow = () => {
    if (newRowIdx.value === null) return;
    rows.value.splice(newRowIdx.value, 1);
    totalRows.value -= 1;
    newRowIdx.value = null;
    newRowData.value = {};
    newRowErrors.value = {};
  };

  /**
   * Returns true when a PK column's value can be auto-generated or safely
   * omitted (the DB has a sequence/default for it):
   *   - UUID columns  → the frontend generates a UUID
   *   - String PKs    → the frontend generates a UUID string
   *   - Serial types  → the DB sequence generates the value
   *
   * Plain integer PKs (int4, int2, int8 …) that are NOT serial are NOT
   * auto-generated and therefore require a user-supplied value.
   */
  const isAutoGeneratedPk = (col: GridColumn): boolean => {
    if (!col.isPrimaryKey) return false;
    const type = col.dataType ? col.dataType.toLowerCase() : '';
    const isUuid = type.includes('uuid') || type === '2950';
    const isStringPk =
      ['1043', '25', '1042'].includes(type) || type.includes('char') || type.includes('text');
    const isSerial = type === 'serial' || type === 'bigserial' || type === 'smallserial';
    return isUuid || isStringPk || isSerial;
  };

  /**
   * Validate a single cell in the new row and store the error (if any).
   * Called on every input change so the user gets immediate feedback.
   */
  const validateNewRowCell = (colName: string, value: string) => {
    const col = columns.value.find((c) => c.name === colName);
    if (!col) return;

    // Auto-generated PK columns have no user-visible error when left empty.
    const isEmpty = !value || value.trim() === '';
    if (isEmpty && isAutoGeneratedPk(col)) {
      const { [colName]: _, ...rest } = newRowErrors.value;
      newRowErrors.value = rest;
      return;
    }

    const result = parseGridInputValue(value, col);
    if (!result.ok) {
      newRowErrors.value = { ...newRowErrors.value, [colName]: result.message };
    } else {
      const { [colName]: _, ...rest } = newRowErrors.value;
      newRowErrors.value = rest;
    }
  };

  /**
   * Validate ALL fields before saving. Returns true when valid.
   * Populates newRowErrors so the UI can highlight every invalid cell.
   */
  const validateAllNewRowFields = (): boolean => {
    const errors: Record<string, string> = {};
    for (const col of columns.value) {
      const val = newRowData.value[col.name] ?? '';
      const isEmpty = !val || val.trim() === '';
      // Skip only genuinely auto-generated PK columns.
      if (isEmpty && isAutoGeneratedPk(col)) continue;
      const result = parseGridInputValue(val, col);
      if (!result.ok) errors[col.name] = result.message;
    }
    newRowErrors.value = errors;
    return Object.keys(errors).length === 0;
  };

  const saveNewRow = async () => {
    if (newRowIdx.value === null) return;
    if (!validateAllNewRowFields()) {
      toastStore.addToast({
        severity: 'error',
        title: 'Validation Failed',
        message: 'Please fix the highlighted fields before saving.'
      });
      return;
    }
    try {
      const cleanData: Record<string, any> = {};
      for (const col of columns.value) {
        const val = newRowData.value[col.name];
        const isEmpty = !val || val === '';

        if (isEmpty && isAutoGeneratedPk(col)) {
          // UUID / string PK → generate a UUID; serial PK → omit (DB handles it).
          const type = col.dataType ? col.dataType.toLowerCase() : '';
          const isUuid = type.includes('uuid') || type === '2950';
          const isStringPk =
            ['1043', '25', '1042'].includes(type) || type.includes('char') || type.includes('text');
          if (isUuid || isStringPk) {
            cleanData[col.name] = crypto.randomUUID();
          }
          // serial → skip entirely so the DB sequence fires
          continue;
        } else {
          const parsed = parseGridInputValue(val, col);
          if (!parsed.ok) throw new Error(parsed.message);
          cleanData[col.name] = parsed.value;
        }
      }

      const savedRow = await insertRowToDB(cleanData);
      rows.value.splice(newRowIdx.value, 1, savedRow);
      newRowIdx.value = null;
      newRowData.value = {};
    } catch (err: any) {
      toastStore.addToast({
        severity: 'error',
        title: 'Insert Failed',
        message: err.message
      });
      throw err;
    }
  };

  const insertRowToDB = async (data: Record<string, any> = {}): Promise<GridRow> => {
    if (!window.NL_PORT) return {};
    const payload = await BridgeService.request('dbBridge.insertRow', 'dbBridge.insertRowResult', {
      connectionId: activeConnectionId.value,
      tableName: resolveBackendTableName(activeTableName.value),
      data
    });
    return payload.row;
  };

  return {
    newRowIdx,
    newRowData,
    newRowErrors,
    createNewRow,
    cancelNewRow,
    saveNewRow,
    validateNewRowCell,
    insertRowToDB
  };
}
