; Script generated by Antigravity for Table-View
#define AppName "Table View"
#ifndef AppVersion
  #define AppVersion "0.2.9"
#endif
#define AppPublisher "Toan Nguyen"
#define AppURL "https://github.com/vantoan1511/table-view"
#define AppExeName "table-view.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{D1A8F9B2-3C4D-5E6F-7A8B-9C0D1E2F3A4B}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={localappdata}\{#AppName}
DisableProgramGroupPage=yes
; The following line allows the user to change the installation path
DisableDirPage=no
; Per-user installation
PrivilegesRequired=lowest
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=..\dist\staging\icon.ico
WizardImageFile=..\icon.png
; Use the same icon for the installer itself

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\staging\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\staging\resources.neu"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\staging\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\staging\extensions\*"; DestDir: "{app}\extensions"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
